services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_start.sh:/ollama_start.sh
      - ollama_data:/root/.ollama
    entrypoint: ['/ollama_start.sh']
    restart: always
    
volumes:
  ollama_data:
